### ISSUE TITLE
Issue with transaction

### ISSUE THREAD

**Issue by davedbase** [calummoore/dgraph-node#9]
Hi there,

I'm trying to make multiple mutations in a transaction with the following code:

    const txn = tasks.reduce(
      (transaction, task, index) => {
        transaction.mutate(
          {
            set: `
              <_:task> <Task> "${uuid.v4()}" .
              <_:task> <ClientID> "${client_id}" .
              <_:task> <Status> "UNASSIGNED" .
              <_:task> <Priority> "${task.Priority}" .
              <_:task> <Created> "${new Date().toISOString()}" .
              <_:task> <Updated> "${new Date().toISOString()}" .
            `,
          },
          false
        );
        return transaction;
      },
      this.client.txn()
    );
    await txn.commit();

However I'm getting the following error returned:

```Illegal value for Message.Field .api.TxnContext.start_ts of type uint64: object (proto3 field without field presence cannot be null)```

I'm using the latest version of Dgraph (1.0.1) and the latest version of the dgraph-node client. I investigated the Transaction object and noticed the following:

    Transaction {
      client: 
       DgraphClient {
         _mutate: [Function],
         _query: [Function],
         _alter: [Function],
         _commitOrAbort: [Function],
         linRead: null,
         config: { url: '127.0.0.1:9080', debug: false } },
      startTs: null,
      linRead: null,
      keys: [] }
    Transaction {
      client: 
       DgraphClient {
         _mutate: [Function],
         _query: [Function],
         _alter: [Function],
         _commitOrAbort: [Function],
         linRead: null,
         config: { url: '127.0.0.1:9080', debug: false } },
      startTs: null,
      linRead: null,
      keys: [] }

Seems like startTs isn't being set and hence causing protobufjs to fail.

**Comment by calummoore** [comment]
On the first transaction, start_ts will be null as we haven't been provided it in a resp from the server. I will look into whether setting it to null causes an issue (instead of just omitting the field).

Also, `transaction.mutate` is async and returns a promise, therefore you should probably wait for each of those to return before starting the next transaction. Even better would be to use the reduce fn to build up the mutation query, and then send it as a single mutation request (to prevent multiple round trips).

It's worth noting that there is now an official JS client, which will probably keep more up to date with changes in Dgraph. 

https://github.com/dgraph-io/dgraph-js

**Comment by calummoore** [comment]
Resolved by 456a37f75ca977d804e8ab6e7c734ea90d737c6a
